table SharePointSites
	lineageTag: c1a00001-0001-0001-0001-000000000001

	column SiteId
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000101
		summarizeBy: none
		sourceColumn: SiteId

		annotation SummarizationSetBy = Automatic

	column SiteUrl
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000102
		summarizeBy: none
		sourceColumn: SiteUrl

		annotation SummarizationSetBy = Automatic

	column DisplayName
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000103
		summarizeBy: none
		sourceColumn: DisplayName

		annotation SummarizationSetBy = Automatic

	column WebTemplate
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000104
		summarizeBy: none
		sourceColumn: WebTemplate

		annotation SummarizationSetBy = Automatic

	column CreatedDateTime
		dataType: dateTime
		lineageTag: c1a00001-0001-0001-0001-000000000105
		summarizeBy: none
		sourceColumn: CreatedDateTime
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column LastModifiedDateTime
		dataType: dateTime
		lineageTag: c1a00001-0001-0001-0001-000000000106
		summarizeBy: none
		sourceColumn: LastModifiedDateTime
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column StorageUsedInBytes
		dataType: int64
		lineageTag: c1a00001-0001-0001-0001-000000000107
		summarizeBy: none
		sourceColumn: StorageUsedInBytes

		annotation SummarizationSetBy = Automatic

	column StorageAllocatedInBytes
		dataType: int64
		lineageTag: c1a00001-0001-0001-0001-000000000108
		summarizeBy: none
		sourceColumn: StorageAllocatedInBytes

		annotation SummarizationSetBy = Automatic

	column IsDeleted
		dataType: boolean
		lineageTag: c1a00001-0001-0001-0001-000000000109
		summarizeBy: none
		sourceColumn: IsDeleted
		formatString: """TRUE"";""TRUE"";""FALSE"""

		annotation SummarizationSetBy = Automatic

	column SensitivityLabelId
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000110
		summarizeBy: none
		sourceColumn: SensitivityLabelId

		annotation SummarizationSetBy = Automatic

	column SensitivityLabelName
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000111
		summarizeBy: none
		sourceColumn: SensitivityLabelName

		annotation SummarizationSetBy = Automatic

	column SharingCapability
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000112
		summarizeBy: none
		sourceColumn: SharingCapability

		annotation SummarizationSetBy = Automatic

	column ConditionalAccessPolicy
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000113
		summarizeBy: none
		sourceColumn: ConditionalAccessPolicy

		annotation SummarizationSetBy = Automatic

	column OwnerEmail
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000114
		summarizeBy: none
		sourceColumn: OwnerEmail

		annotation SummarizationSetBy = Automatic

	column OwnerDisplayName
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000115
		summarizeBy: none
		sourceColumn: OwnerDisplayName

		annotation SummarizationSetBy = Automatic

	column GroupId
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000116
		summarizeBy: none
		sourceColumn: GroupId

		annotation SummarizationSetBy = Automatic

	column IsTeamsConnected
		dataType: boolean
		lineageTag: c1a00001-0001-0001-0001-000000000117
		summarizeBy: none
		sourceColumn: IsTeamsConnected
		formatString: """TRUE"";""TRUE"";""FALSE"""

		annotation SummarizationSetBy = Automatic

	column LockState
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000118
		summarizeBy: none
		sourceColumn: LockState

		annotation SummarizationSetBy = Automatic

	column HubSiteId
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000119
		summarizeBy: none
		sourceColumn: HubSiteId

		annotation SummarizationSetBy = Automatic

	column DeviceAccessPolicy
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000120
		summarizeBy: none
		sourceColumn: DeviceAccessPolicy

		annotation SummarizationSetBy = Automatic

	column GeoLocation
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000121
		summarizeBy: none
		sourceColumn: GeoLocation

		annotation SummarizationSetBy = Automatic

	column SnapshotDate
		dataType: dateTime
		lineageTag: c1a00001-0001-0001-0001-000000000122
		summarizeBy: none
		sourceColumn: SnapshotDate
		formatString: General Date

		annotation SummarizationSetBy = Automatic

	column CalcSiteRiskScore =
		VAR _ExternalSharing = IF([SharingCapability] IN {"ExternalUserAndGuestSharing", "ExternalUserSharingOnly"}, 25, 0)
		VAR _NoLabel = IF(ISBLANK([SensitivityLabelId]), 20, 0)
		VAR _NoDevicePolicy = IF(ISBLANK([DeviceAccessPolicy]), 15, 0)
		VAR _Orphaned = IF(ISBLANK([OwnerEmail]), 15, 0)
		VAR _Stale = IF(DATEDIFF([LastModifiedDateTime], TODAY(), DAY) > 180, 15, 0)
		VAR _NoConditionalAccess = IF(ISBLANK([ConditionalAccessPolicy]), 10, 0)
		RETURN _ExternalSharing + _NoLabel + _NoDevicePolicy + _Orphaned + _Stale + _NoConditionalAccess
		dataType: int64
		lineageTag: c1a00001-0001-0001-0001-000000000201
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SiteRiskTier =
		SWITCH(
			TRUE(),
			[CalcSiteRiskScore] >= 75, "Critical",
			[CalcSiteRiskScore] >= 50, "High",
			[CalcSiteRiskScore] >= 25, "Medium",
			"Low"
		)
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000202
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column SiteType =
		SWITCH(
			TRUE(),
			[WebTemplate] = "SITEPAGEPUBLISHING#0", "Communication",
			CONTAINSSTRING([SiteUrl], "-my.sharepoint.com"), "Personal",
			"Team"
		)
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000203
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column StorageUsedGB =
		DIVIDE([StorageUsedInBytes], 1073741824, 0)
		dataType: double
		lineageTag: c1a00001-0001-0001-0001-000000000204
		summarizeBy: none
		formatString: #,0.00

		annotation SummarizationSetBy = Automatic

	column DaysSinceModified =
		DATEDIFF([LastModifiedDateTime], TODAY(), DAY)
		dataType: int64
		lineageTag: c1a00001-0001-0001-0001-000000000205
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ExternalSharingRiskLevel =
		SWITCH(
			[SharingCapability],
			"ExternalUserAndGuestSharing", "Critical",
			"ExternalUserSharingOnly", "High",
			"ExistingExternalUserSharingOnly", "Medium",
			"Low"
		)
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000206
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsOrphaned =
		ISBLANK([OwnerEmail])
		dataType: boolean
		lineageTag: c1a00001-0001-0001-0001-000000000207
		summarizeBy: none
		formatString: """TRUE"";""TRUE"";""FALSE"""

		annotation SummarizationSetBy = Automatic

	column HasSensitivityLabel =
		NOT(ISBLANK([SensitivityLabelId]))
		dataType: boolean
		lineageTag: c1a00001-0001-0001-0001-000000000208
		summarizeBy: none
		formatString: """TRUE"";""TRUE"";""FALSE"""

		annotation SummarizationSetBy = Automatic

	column StorageUtilizationPct =
		DIVIDE([StorageUsedInBytes], [StorageAllocatedInBytes], 0) * 100
		dataType: double
		lineageTag: c1a00001-0001-0001-0001-000000000209
		summarizeBy: none
		formatString: #,0.00

		annotation SummarizationSetBy = Automatic

	column SiteAgeCategory =
		SWITCH(
			TRUE(),
			DATEDIFF([CreatedDateTime], TODAY(), DAY) < 90, "New",
			DATEDIFF([CreatedDateTime], TODAY(), DAY) < 365, "Recent",
			DATEDIFF([CreatedDateTime], TODAY(), DAY) < 730, "Established",
			"Mature"
		)
		dataType: string
		lineageTag: c1a00001-0001-0001-0001-000000000210
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column IsOverprovisioned =
		[StorageUtilizationPct] < 5 && [StorageAllocatedInBytes] > 1073741824
		dataType: boolean
		lineageTag: c1a00001-0001-0001-0001-000000000211
		summarizeBy: none
		formatString: """TRUE"";""TRUE"";""FALSE"""

		annotation SummarizationSetBy = Automatic

	partition SharePointSites = m
		mode: import
		source =
			let
			    Source = Sql.Database(LakehouseSQLEndpoint, LakehouseName),
			    SharePoint_Sites = Source{[Schema="dbo", Item="SharePoint_Sites_v1"]}[Data],
			    Typed = Table.TransformColumnTypes(SharePoint_Sites, {
			        {"SiteId", type text}, {"SiteUrl", type text}, {"DisplayName", type text},
			        {"WebTemplate", type text}, {"CreatedDateTime", type datetimezone},
			        {"LastModifiedDateTime", type datetimezone}, {"StorageUsedInBytes", Int64.Type},
			        {"StorageAllocatedInBytes", Int64.Type}, {"IsDeleted", type logical},
			        {"SensitivityLabelId", type text}, {"SensitivityLabelName", type text},
			        {"SharingCapability", type text}, {"ConditionalAccessPolicy", type text},
			        {"OwnerEmail", type text}, {"OwnerDisplayName", type text},
			        {"GroupId", type text}, {"IsTeamsConnected", type logical},
			        {"LockState", type text}, {"HubSiteId", type text},
			        {"DeviceAccessPolicy", type text}, {"GeoLocation", type text},
			        {"SnapshotDate", type datetimezone}
			    })
			in
			    Typed

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table
